


# This is a basic workflow to help you get started with Actions

name: BCS-LB-Test

on:
  workflow_dispatch:
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

jobs:
 
  Liquibasejob:
    #runs-on: self-hosted 
    runs-on: windows-latest
   
    steps:
        - name: runLBTest
          uses: actions/checkout@v2

        - run: ./liquibase/liquibase --version

